-- Exact read-only statements executed on 2026-10-05. Owner-level connector;
-- read-only transactions and bounded timeouts, no hosted writes.
-- The connector returned only the last SELECT of block 1; block 2 repeats sizes.
-- Block 5 originally had an alias syntax error; corrected query below succeeded.

-- Block 1
BEGIN READ ONLY; SET LOCAL statement_timeout='10s'; SET LOCAL lock_timeout='2s';
SELECT current_user AS role, current_setting('transaction_read_only') AS read_only, now() AS checked_at, (SELECT sum(pg_database_size(datname))::bigint FROM pg_database) AS cluster_bytes, pg_database_size(current_database()) AS current_database_bytes;
SELECT n.nspname,c.relname,pg_total_relation_size(c.oid) AS total_bytes,pg_relation_size(c.oid) AS heap_bytes,pg_indexes_size(c.oid) AS index_bytes, CASE WHEN c.reltoastrelid=0 THEN 0 ELSE pg_total_relation_size(c.reltoastrelid) END AS toast_bytes,s.n_live_tup,s.n_dead_tup,s.n_tup_ins,s.n_tup_upd,s.n_tup_del,s.last_autovacuum,s.last_vacuum FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace LEFT JOIN pg_stat_user_tables s ON s.relid=c.oid WHERE n.nspname IN ('quant_app','equity_research') AND c.relkind='r' ORDER BY pg_total_relation_size(c.oid) DESC LIMIT 12; ROLLBACK;

-- Block 2
BEGIN READ ONLY; SET LOCAL statement_timeout='10s'; SET LOCAL lock_timeout='2s';
SELECT jsonb_build_object('checked_at',now(),'role',current_user,'read_only',current_setting('transaction_read_only'),'cluster_bytes',(SELECT sum(pg_database_size(datname))::bigint FROM pg_database),'current_database_bytes',pg_database_size(current_database()),'derivative_tables',(SELECT count(*) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname IN ('derivatives_reference','derivatives_monitor') AND c.relkind='r'),'stats_reset',(SELECT stats_reset FROM pg_stat_database WHERE datname=current_database()),'outcomes',(SELECT jsonb_build_object('rows',count(*),'stored_payload_bytes',sum(pg_column_size(payload)),'latest_decisions',count(DISTINCT decision_id),'newest_recorded',max(recorded_at)) FROM equity_research.outcomes),'universe_versions',(SELECT jsonb_agg(x) FROM (SELECT snapshot_date,count(*) AS versions,count(DISTINCT payload_hash) AS hashes,sum(instrument_count) AS members FROM quant_app.universe_snapshot_versions GROUP BY snapshot_date ORDER BY snapshot_date DESC LIMIT 8) x),'ledger',(SELECT jsonb_agg(x) FROM (SELECT recorded_at::date AS day,event_type,count(*) AS events,sum(pg_column_size(payload)) AS stored_payload_bytes FROM quant_app.evidence_ledger_events WHERE recorded_at>=current_date-interval '7 days' GROUP BY 1,2 ORDER BY 1 DESC,2) x),'archives',(SELECT jsonb_agg(x) FROM (SELECT source_table,max(completed_at) AS latest_completed,sum(deleted_count) FILTER(WHERE completed_at>=current_date) AS today_deleted FROM quant_app.archive_manifests GROUP BY source_table) x)); ROLLBACK;

-- Block 3
BEGIN READ ONLY; SET LOCAL statement_timeout='10s'; SET LOCAL lock_timeout='2s'; SELECT jsonb_build_object('outcome_eligible',(SELECT count(*) FROM equity_research.outcomes s WHERE s.recorded_at<(current_date-7)::timestamp AT TIME ZONE 'UTC' AND EXISTS(SELECT 1 FROM equity_research.outcomes newer WHERE newer.decision_id=s.decision_id AND (newer.recorded_at,newer.snapshot_id)>(s.recorded_at,s.snapshot_id))),'nav_eligible',(SELECT count(*) FROM quant_app.mf_nav s WHERE s.nav_date<current_date-14 AND EXISTS(SELECT 1 FROM quant_app.mf_nav n WHERE n.scheme_code=s.scheme_code AND n.nav_date>s.nav_date)),'quote_eligible',(SELECT count(*) FROM quant_app.market_quotes s WHERE s.trade_date<current_date-14 AND s.observed_at<(current_date-14)::timestamp AT TIME ZONE 'UTC'),'ledger_today',(SELECT jsonb_build_object('events',count(*),'payload_bytes',sum(pg_column_size(payload))) FROM quant_app.evidence_ledger_events WHERE recorded_at>=current_date),'canonical_dates',(SELECT jsonb_agg(x) FROM(SELECT snapshot_date,count(*) AS members FROM quant_app.universe_membership GROUP BY snapshot_date ORDER BY snapshot_date DESC LIMIT 20)x)); ROLLBACK;

-- Block 4
BEGIN READ ONLY; SET LOCAL statement_timeout='10s'; SET LOCAL lock_timeout='2s'; WITH latest AS (SELECT snapshot_id,row_number() OVER(ORDER BY observed_at DESC,snapshot_id) AS rn FROM quant_app.universe_snapshot_versions WHERE snapshot_date=current_date), pairs AS(SELECT a.raw AS old,b.raw AS new FROM quant_app.universe_membership_versions a JOIN quant_app.universe_membership_versions b USING(instrument_key) WHERE a.snapshot_id=(SELECT snapshot_id FROM latest WHERE rn=2) AND b.snapshot_id=(SELECT snapshot_id FROM latest WHERE rn=1)), changed AS(SELECT k FROM pairs CROSS JOIN LATERAL (SELECT key AS k FROM jsonb_object_keys(old||new) key) f WHERE old->k IS DISTINCT FROM new->k) SELECT jsonb_build_object('changed_master_fields',(SELECT jsonb_object_agg(k,num) FROM(SELECT k,count(*) AS num FROM changed GROUP BY k)x),'roles',(SELECT jsonb_agg(jsonb_build_object('name',rolname,'login',rolcanlogin,'superuser',rolsuper,'bypass_rls',rolbypassrls)) FROM pg_roles WHERE rolname IN('quant_app_runtime','quant_archive_worker','equity_research_collector','quant_derivative_ingestor','quant_derivative_monitor','quant_derivative_watchdog')),'long_transactions',(SELECT count(*) FROM pg_stat_activity WHERE xact_start<now()-interval '5 minutes' AND pid<>pg_backend_pid()),'prepared_transactions',(SELECT count(*) FROM pg_prepared_xacts),'slots',(SELECT count(*) FROM pg_replication_slots),'running_vacuum',(SELECT count(*) FROM pg_stat_progress_vacuum)); ROLLBACK;

-- Block 5
BEGIN READ ONLY; SET LOCAL statement_timeout='10s'; SET LOCAL lock_timeout='2s'; SELECT jsonb_build_object('nav_shorter_window_candidate',(SELECT count(*) FROM quant_app.mf_nav s WHERE nav_date<current_date-1 AND EXISTS(SELECT 1 FROM quant_app.mf_nav n WHERE n.scheme_code=s.scheme_code AND n.nav_date>s.nav_date)),'foreign_keys',(SELECT jsonb_agg(jsonb_build_object('name',conname,'definition',pg_get_constraintdef(oid))) FROM pg_constraint WHERE contype='f' AND (confrelid='quant_app.mf_nav'::regclass OR confrelid='quant_app.evidence_ledger_events'::regclass OR confrelid='equity_research.outcomes'::regclass)),'ledger_day_bytes',(SELECT jsonb_agg(x) FROM(SELECT recorded_at::date AS day,count(*) events,sum(pg_column_size(payload)) payload_bytes FROM quant_app.evidence_ledger_events GROUP BY 1 ORDER BY 1 DESC LIMIT 8)x)); ROLLBACK;

